global:
  scrape_interval:     10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'consent-manager'
    static_configs:
      - targets: ['${CONSENT_MANAGER}']
  - job_name: 'contract-manager'
    static_configs:
      - targets: ['${CONTRACT_MANAGER}']
  - job_name: 'catalog'
    static_configs:
      - targets: ['${CATALOG}']
  - job_name: 'catalog-registry'
    static_configs:
      - targets: ['${CATALOG_REGISTRY}']
