global:
  scrape_interval:     10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'consent-manager'
    static_configs:
      - targets: ['consent-manager:${CONSENT_MANAGER_PORT}']
  - job_name: 'contract-manager'
    static_configs:
      - targets: ['contract-manager:${CONTRACT_MANAGER_PORT}']
  - job_name: 'catalog'
    static_configs:
      - targets: ['catalog:${CATALOG_PORT}']
  - job_name: 'catalog-registry'
    static_configs:
      - targets: ['catalog-registry:${CATALOG_REGISTRY_PORT}']
