apiVersion: v1
kind: Secret
metadata:
  name: env-vars
  namespace: monitoring
type: Opaque
data:
  PROM_PORT: { { .Values.env.PROM_PORT | b64enc } }
  ALERT_PORT: { { .Values.env.PROM_PORT | b64enc } }
  GRAFANA_PORT: { { .Values.env.GRAFANA_PORT | b64enc } }
  GRAFANA_ADMIN_USER: { { .Values.env.GRAFANA_ADMIN_USER | b64enc } }
  GRAFANA_ADMIN_PWD: { { .Values.env.GRAFANA_ADMIN_PWD | b64enc } }
  CONSENT_MANAGER: { { .Values.env.CONSENT_MANAGER | b64enc } }
  CONTRACT_MANAGER: { { .Values.env.CONTRACT_MANAGER | b64enc } }
  CATALOG : { { .Values.env.CATALOG | b64enc } }
  CATALOG_REGISTRY: { { .Values.env.CATALOG_REGISTRY | b64enc } }
